SOURCES_CXX :=
SOURCES_C   :=

LIBRETRO_COMM_DIR := $(CORE_DIR)/libretro-common
MEDNAFEN_DIR := $(CORE_DIR)/mednafen
CORE_EMU_DIR := $(MEDNAFEN_DIR)/pce_fast
CDROM_DIR         := $(MEDNAFEN_DIR)/cdrom

INCFLAGS := \
	-I$(CORE_DIR) \
	-I$(MEDNAFEN_DIR) \
	-I$(MEDNAFEN_DIR)/include \
	-I$(MEDNAFEN_DIR)/intl \
	-I$(MEDNAFEN_DIR)/hw_sound \
	-I$(MEDNAFEN_DIR)/hw_cpu \
	-I$(MEDNAFEN_DIR)/hw_misc \
	-I$(LIBRETRO_COMM_DIR)/include

# CHD images are read by libretro-common's clean-room rchd reader. Its hunk
# codecs come from the same tree: zlib-format hunks through
# encoding_deflate.c, LZMA through r7z_lzma.c, FLAC through rflac.c, zstd
# through encoding_rzstd.c, and the version 5 map through
# encoding_huffman.c, which every image needs to open at all.
CHD_SOURCES_C = \
	$(CDROM_DIR)/chd_image.c \
	$(LIBRETRO_COMM_DIR)/formats/chd/rchd.c \
	$(LIBRETRO_COMM_DIR)/encodings/encoding_huffman.c \
	$(LIBRETRO_COMM_DIR)/encodings/encoding_rzstd.c \
	$(LIBRETRO_COMM_DIR)/encodings/encoding_deflate.c \
	$(LIBRETRO_COMM_DIR)/formats/7z/r7z_lzma.c \
	$(LIBRETRO_COMM_DIR)/formats/flac/rflac.c

ifneq ($(HAVE_GRIFFIN),1)
	SOURCES_CXX += \
		$(CORE_EMU_DIR)/pce.cpp \
		$(CORE_EMU_DIR)/huc.cpp \
		$(CORE_EMU_DIR)/huc6280.cpp \
		$(CORE_EMU_DIR)/input.cpp \
		$(CORE_EMU_DIR)/pcecd.cpp \
		$(CORE_EMU_DIR)/pcecd_drive.cpp \
		$(CORE_EMU_DIR)/psg.cpp \
		$(CORE_EMU_DIR)/vdc.cpp \
		$(MEDNAFEN_DIR)/hw_misc/arcade_card/arcade_card.cpp
endif

ifeq ($(NEED_BLIP), 1)
	SOURCES_CXX += $(MEDNAFEN_DIR)/sound/Blip_Buffer.cpp
endif

ifeq ($(HAVE_HES), 1)
	SOURCES_CXX += $(CORE_EMU_DIR)/hes.cpp
endif

ifeq ($(NEED_DEINTERLACER), 1)
	FLAGS += -DNEED_DEINTERLACER
endif

ifeq ($(IS_X86), 1)
	FLAGS += -DARCH_X86
endif

ifeq ($(NEED_BPP), 8)
	FLAGS += -DWANT_8BPP
endif

ifeq ($(NEED_BPP), 16)
	FLAGS += -DWANT_16BPP
endif

ifeq ($(NEED_BPP), 32)
	FLAGS += -DWANT_32BPP
endif

ifeq ($(NO_COMPUTED_GOTO), 1)
	FLAGS += -DNO_COMPUTED_GOTO
endif

ifeq ($(NEED_STEREO_SOUND), 1)
	FLAGS += -DWANT_STEREO_SOUND
endif

ifeq ($(FRONTEND_SUPPORTS_RGB565), 1)
	FLAGS += -DFRONTEND_SUPPORTS_RGB565
endif

ifeq ($(CACHE_CD), 1)
	FLAGS += -D__LIBRETRO_CACHE_CD__
endif

ifeq ($(NEED_CD), 1)
	ifneq ($(HAVE_GRIFFIN),1)
		SOURCES_CXX += $(MEDNAFEN_DIR)/cdrom/CDAccess.cpp \
			$(MEDNAFEN_DIR)/cdrom/CDAccess_Image.cpp \
			$(MEDNAFEN_DIR)/cdrom/CDAccess_CCD.cpp \
			$(MEDNAFEN_DIR)/cdrom/audioreader.cpp \
			$(MEDNAFEN_DIR)/cdrom/cdromif.cpp

		ifeq ($(HAVE_CDROM), 1)
			SOURCES_C += \
							$(LIBRETRO_COMM_DIR)/cdrom/cdrom.c \
							$(LIBRETRO_COMM_DIR)/vfs/vfs_implementation_cdrom.c
		endif

		SOURCES_C += $(MEDNAFEN_DIR)/cdrom/CDUtility.c \
			$(MEDNAFEN_DIR)/cdrom/lec.c \
			$(MEDNAFEN_DIR)/cdrom/galois.c \
			$(MEDNAFEN_DIR)/cdrom/recover-raw.c \
			$(MEDNAFEN_DIR)/cdrom/l-ec.c \
			$(MEDNAFEN_DIR)/cdrom/edc_crc32.c
	endif
	FLAGS += -DNEED_CD
endif

ifeq ($(HAVE_CHD), 1)
	# The HAVE_RCHD_* flags name the hunk codecs rchd is built with;
	# chd_image.c refuses to build without all four.
	FLAGS += -DHAVE_CHD -DHAVE_RCHD -DHAVE_RCHD_DEFLATE -DHAVE_RCHD_LZMA \
		-DHAVE_RCHD_FLAC -DHAVE_RCHD_ZSTD -DHAVE_RFLAC -DHAVE_RZSTD
	SOURCES_C += $(CHD_SOURCES_C)
	SOURCES_CXX += $(CDROM_DIR)/CDAccess_CHD.cpp
endif

ifeq ($(NEED_TREMOR), 1)
	SOURCES_C += $(wildcard $(MEDNAFEN_DIR)/tremor/*.c)
	FLAGS += -DNEED_TREMOR
endif

ifneq ($(HAVE_GRIFFIN), 1)
	SOURCES_CXX += \
		$(MEDNAFEN_DIR)/error.cpp \
		$(MEDNAFEN_DIR)/settings.cpp \
		$(MEDNAFEN_DIR)/general.cpp \
		$(MEDNAFEN_DIR)/FileWrapper.cpp \
		$(MEDNAFEN_DIR)/FileStream.cpp \
		$(MEDNAFEN_DIR)/MemoryStream.cpp \
		$(MEDNAFEN_DIR)/Stream.cpp \
		$(MEDNAFEN_DIR)/state.cpp \
		$(MEDNAFEN_DIR)/mempatcher.cpp \
		$(MEDNAFEN_DIR)/okiadpcm.cpp \
		$(MEDNAFEN_DIR)/endian.cpp \
		$(MEDNAFEN_DIR)/video/surface.cpp \
		$(CORE_DIR)/libretro.cpp

	SOURCES_C += \
		$(MEDNAFEN_DIR)/file.c
endif

ifneq ($(STATIC_LINKING), 1)
	SOURCES_C += $(LIBRETRO_COMM_DIR)/streams/file_stream.c \
			$(LIBRETRO_COMM_DIR)/streams/file_stream_transforms.c \
			$(LIBRETRO_COMM_DIR)/file/file_path.c \
			$(LIBRETRO_COMM_DIR)/file/file_path_io.c \
			$(LIBRETRO_COMM_DIR)/file/retro_dirent.c \
			$(LIBRETRO_COMM_DIR)/lists/string_list.c \
			$(LIBRETRO_COMM_DIR)/lists/dir_list.c \
			$(LIBRETRO_COMM_DIR)/compat/compat_strl.c \
			$(LIBRETRO_COMM_DIR)/compat/compat_snprintf.c \
			$(LIBRETRO_COMM_DIR)/compat/compat_posix_string.c \
			$(LIBRETRO_COMM_DIR)/compat/fopen_utf8.c \
			$(LIBRETRO_COMM_DIR)/compat/compat_strcasestr.c \
			$(LIBRETRO_COMM_DIR)/encodings/encoding_utf.c \
			$(LIBRETRO_COMM_DIR)/encodings/encoding_crc32.c \
			$(LIBRETRO_COMM_DIR)/features/features_cpu.c \
			$(LIBRETRO_COMM_DIR)/vfs/vfs_implementation.c \
			$(LIBRETRO_COMM_DIR)/memmap/memalign.c \
			$(LIBRETRO_COMM_DIR)/string/stdstring.c \
			$(LIBRETRO_COMM_DIR)/string/rstrtod.c \
			$(LIBRETRO_COMM_DIR)/time/rtime.c
endif
